background: &background "ffffffff"
foreground: &foreground "000000ff"
foreground_dim: &foreground_dim "4e4e4e95"
color_attention: &color_attention "c9007aff"
color_focused: &color_focused "ffec00ff"
color_charging: &color_charging "152eafff"

dmargin: &dmargin 16
margin: &margin 8
margin-side: &margin-side 4

bar:
  height: 26
  location: top
  background: *background
  foreground: *foreground
  font: monospace:pixelsize=18
  spacing: *margin
  margin: *margin
  trackpad-sensitivity: 40

  left:
    - battery:
        name: BAT0
        content:
          map:
            default:
              ramp:
                tag: capacity
                items:
                  - string: {text: "󰂎 {capacity}%"}
                  - string: {text: "󰁺 {capacity}%"}
                  - string: {text: "󰁼 {capacity}%"}
                  - string: {text: "󰁽 {capacity}%"}
                  - string: {text: "󰁾 {capacity}%"}
                  - string: {text: "󰁿 {capacity}%"}
                  - string: {text: "󰂀 {capacity}%"}
                  - string: {text: "󰂁 {capacity}%"}
                  - string: {text: "󰂂 {capacity}%"}
                  - string: {text: "󰁹 {capacity}%"}

            conditions:
              state == "charging":
                ramp:
                  foreground: *color_charging
                  tag: capacity
                  items:
                    - string: {text: "󰢜 {capacity}%"}
                    - string: {text: "󰂆 {capacity}%"}
                    - string: {text: "󰂇 {capacity}%"}
                    - string: {text: "󰂈 {capacity}%"}
                    - string: {text: "󰢝 {capacity}%"}
                    - string: {text: "󰂉 {capacity}%"}
                    - string: {text: "󰢞 {capacity}%"}
                    - string: {text: "󰂊 {capacity}%"}
                    - string: {text: "󰂋 {capacity}%"}
                    - string: {text: "󰂅 {capacity}%"}

    - backlight:
        name: intel_backlight
        content:
          string:
            text: "󰛨 {percent}%"
            on-click:
              wheel-up: "brightnessctl s 2%+"
              wheel-down: "brightnessctl s 2%-"

    - pipewire:
        content:
          map:
            on-click:
              wheel-up: pamixer -i 2
              wheel-down: pamixer -d 2
              left: footclient -T pulsemixer pulsemixer
              right: pamixer -t

            conditions:
              muted && type == "sink":
                string: {text: "󰸈 {cubic_volume}%", foreground: *color_attention}
              ~muted && type == "sink":
                ramp:
                  tag: cubic_volume
                  items:
                    - string: {text: " {cubic_volume}%"}
                    - string: {text: "󰖀 {cubic_volume}%"}
                    - string: {text: "󰕾 {cubic_volume}%"}

    - script:
        path: ~/.local/bin/antenna
        args:
          - "-y bluetooth"
        poll-interval: 3000
        content:
          map:
            on-click:
              left: sh -c "antenna -c bluetooth && bt -c"
              right: "antenna -t bluetooth"
            conditions:
              bluetooth: {string: {text: 󰂯}}
              ~bluetooth: {string: {text: 󰂲, foreground: *color_attention}}

    - network:
        spacing: 0
        content:
          map:
            right-margin: *dmargin
            on-click:
              left: "notify-send 'TODO: Implement bring up network manager'"
              right: "antenna -t wifi"

            conditions:
              name == "enp0s31f6" && state == "up":
                string: {text: 󰈀}
              name == "wlan0":
                map:
                  default:
                    string: {text: 󰤭, foreground: *color_attention}
                  conditions:
                    ssid != "":
                      ramp:
                        tag: quality
                        items:
                          - string: {text: "󰤯 {ssid}"}
                          - string: {text: "󰤟 {ssid}"}
                          - string: {text: "󰤢 {ssid}"}
                          - string: {text: "󰤥 {ssid}"}
                          - string: {text: "󰤨 {ssid}"}
    - script:
        path: /usr/bin/yambar-hyprland-wses
        anchors:
          ws_empty: &ws_empty 555555ff
          ws_other: &ws_other bbbbbbff
          # you can use `{workspace_N}` here to use the workspace name
          # assigned by Hyprland instead of hard-coding one here. That
          # name is, as far as I can tell, always just the index of the
          # workspace though, so not all that valuable.
          ws_1: &ws_1 ""
          ws_2: &ws_2 "󰙨"
          ws_3: &ws_3 "󰈙"
          ws_4: &ws_4 ""
          ws_5: &ws_5 "󰍦"
          ws_6: &ws_6 ""
          ws_7: &ws_7 ""
          ws_8: &ws_8 ""
        content:
          list:
            spacing: 0
            items:
              - map:
                  on-click:
                    left: sh -c "hyprctl dispatch workspace 1"
                  default:
                    string: { text: *ws_1, margin: *margin, deco: { background: {color: *background} }}
                  conditions:
                    workspace_count < 2:
                      empty: {}
                    workspace_1_focused:
                      string: { text: *ws_1, margin: *margin, deco: { background: {color: *color_focused} }}
                    workspace_1_active:
                      string: { text: *ws_1, margin: *margin, deco: { background: {color: *color_attention} }}
                    workspace_1_windows == 0:
                      empty: {}
              - map:
                  on-click:
                    left: sh -c "hyprctl dispatch workspace 2"
                  default:
                    string: { text: *ws_2, margin: *margin, deco: { background: {color: *background} }}
                  conditions:
                    workspace_count < 3:
                      empty: {}
                    workspace_2_focused:
                      string: { text: *ws_2, margin: *margin, deco: { background: {color: *color_focused} }}
                    workspace_2_active:
                      string: { text: *ws_2, margin: *margin, deco: { background: {color: *color_attention} }}
                    workspace_2_windows == 0:
                      empty: {}
              - map:
                  on-click:
                    left: sh -c "hyprctl dispatch workspace 3"
                  default:
                    string: { text: *ws_3, margin: *margin, deco: { background: {color: *background} }}
                  conditions:
                    workspace_count < 4:
                      empty: {}
                    workspace_3_focused:
                      string: { text: *ws_3, margin: *margin, deco: { background: {color: *color_focused} }}
                    workspace_3_active:
                      string: { text: *ws_3, margin: *margin, deco: { background: {color: *color_attention} }}
                    workspace_3_windows == 0:
                      empty: {}
              - map:
                  on-click:
                    left: sh -c "hyprctl dispatch workspace 4"
                  default:
                    string: { text: *ws_4, margin: *margin, deco: { background: {color: *background} }}
                  conditions:
                    workspace_count < 5:
                      empty: {}
                    workspace_4_focused:
                      string: { text: *ws_4, margin: *margin, deco: { background: {color: *color_focused} }}
                    workspace_4_active:
                      string: { text: *ws_4, margin: *margin, deco: { background: {color: *color_attention} }}
                    workspace_4_windows == 0:
                      empty: {}
              - map:
                  on-click:
                    left: sh -c "hyprctl dispatch workspace 5"
                  default:
                    string: { text: *ws_5, margin: *margin, deco: { background: {color: *background} }}
                  conditions:
                    workspace_count < 6:
                      empty: {}
                    workspace_5_focused:
                      string: { text: *ws_5, margin: *margin, deco: { background: {color: *color_focused} }}
                    workspace_5_active:
                      string: { text: *ws_5, margin: *margin, deco: { background: {color: *color_attention} }}
                    workspace_5_windows == 0:
                      empty: {}
              - map:
                  on-click:
                    left: sh -c "hyprctl dispatch workspace 6"
                  default:
                    string: { text: *ws_6, margin: *margin, deco: { background: {color: *background} }}
                  conditions:
                    workspace_count < 7:
                      empty: {}
                    workspace_6_focused:
                      string: { text: *ws_6, margin: *margin, deco: { background: {color: *color_focused} }}
                    workspace_6_active:
                      string: { text: *ws_6, margin: *margin, deco: { background: {color: *color_attention} }}
                    workspace_6_windows == 0:
                      empty: {}
              - map:
                  on-click:
                    left: sh -c "hyprctl dispatch workspace 7"
                  default:
                    string: { text: *ws_7, margin: *margin, deco: { background: {color: *background} }}
                  conditions:
                    workspace_count < 8:
                      empty: {}
                    workspace_7_focused:
                      string: { text: *ws_7, margin: *margin, deco: { background: {color: *color_focused} }}
                    workspace_7_active:
                      string: { text: *ws_7, margin: *margin, deco: { background: {color: *color_attention} }}
                    workspace_7_windows == 0:
                      empty: {}
              - map:
                  on-click:
                    left: sh -c "hyprctl dispatch workspace 8"
                  default:
                    string: { text: *ws_8, margin: *margin, deco: { background: {color: *background} }}
                  conditions:
                    workspace_count < 9:
                      empty: {}
                    workspace_8_focused:
                      string: { text: *ws_8, margin: *margin, deco: { background: {color: *color_focused} }}
                    workspace_8_active:
                      string: { text: *ws_8, margin: *margin, deco: { background: {color: *color_attention} }}
                    workspace_8_windows == 0:
                      empty: {}

  right:
    - mpd:
        port: 6600
        host: "127.0.0.1"
        content:
          map:
            on-click:
              left: "mpc toggle"
              right: sh -c "riverctl set-focused-tags $((1 << 4)) && pgrep rmpc || setsid -f footclient rmpc"
            conditions:
              state == stopped:
                - string: {text: 󰝛}
                - string: {text: " Stopped", foreground: *foreground_dim }
              state == offline:
                - string: {text: 󰝛}
                - string: {text: " Offline", foreground: *foreground_dim }
              (state == paused || state == playing) && (artist != "" && title != ""):
                list:
                  spacing: 0
                  items:
                    - string: {text: "󰝚 "}
                    - map:
                        conditions:
                          state == playing: {string: {text: "{artist}", foreground: *color_charging}}
                          state == paused: {string: {text: "{artist}", foreground: *foreground_dim}}
                    - map:
                        conditions:
                          state == playing: {string: {text: " | ", foreground: *foreground}}
                          state == paused: {string: {text: " | ", foreground: *foreground_dim}}
                    - map:
                        conditions:
                          state == playing: {string: {text: "{title}", foreground: *color_attention}}
                          state == paused: {string: {text: "{title}", foreground: *foreground_dim}}
                    - map:
                        conditions:
                          state == playing: {string: {text: " | ", foreground: *foreground}}
                          state == paused: {string: {text: " | ", foreground: *foreground_dim}}
                    - map:
                        conditions:
                          state == playing: {string: {text: "{pos}/{end}", foreground: *foreground}}
                          state == paused: {string: {text: "{pos}/{end}", foreground: *foreground_dim}}
              (state == paused || state == playing):
                list:
                  spacing: 0
                  items:
                    - string: {text: "󰝚 "}
                    - map:
                        conditions:
                          state == playing: {string: {text: "{file}"}}
                          state == paused: {string: {text: "{file}", foreground: *foreground_dim}}
                    - map:
                        conditions:
                          state == playing: {string: {text: " | {pos}/{end}"}}
                          state == paused: {string: {text: " | {pos}/{end}", foreground: *foreground_dim}}

    - clock:
        date-format: "%a %d/%m/%Y"
        content:
          - string: { text: " {date}", right-margin: *margin-side, on-click: sh -c "riverctl set-focused-tags $((1 << 5)) && setsid -f gnome-calendar" }
          - string: { text: "󱑃 {time}", left-margin: *margin-side }

    - label:
        content:
          string:
            on-click: "wlogout"
            text: 󰐥
